version: '3.4'
services:
  symfony:
    container_name: symfony
    build:
      context: ./symfony
      dockerfile: ./Dockerfile
    image: sikora00/docker-symfony
    environment:
      - DEBUG=true
      - VIRTUAL_HOST=symfony.local
      - VIRTUAL_PORT=80
    volumes:
      - ./symfony:/var/www/html
    ports:
      - 8080:80
    networks:
      - reverse-proxy
      - network
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3366:3306
    networks:
      - network

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  network:
    driver: bridge
